status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = ESJsonLayout
appender.console.layout.type_name = server
appender.console.layout.timezone = Asia/Shanghai

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
